### ISSUE TITLE
How to get Item ID (api)?

### ISSUE THREAD

**Issue by balex25** [samhoogantink/Fortnite-API#11]
Hello,

I see on the official Epic Games API a different ID and on your API it is not the same for skin.

EX:
Item name: Chromatic Wrap

_Official API_
offerId: **11fb033c9cf9e251b35b7487cdea9357135054de607c011913609b06eae7d8d9** 

_Fortniteapi.com_
Item ID (api): **d633710-bf33be9-4821704-8e006cf**

I have an app that needs to use the official API and some part from your API, but I don't know how to convert or to get the same Item ID from the official API.

Many thanks and keep great work with API! 👍

**Comment by samhoogantink** [comment]
Hi,

The offerId is not the user ID. I'm using my own generated id.

Can you contact me on Discord or Twitter?
