### ISSUE TITLE
Problem Gettting User id

### ISSUE THREAD

**Issue by hadouken111** [samhoogantink/Fortnite-API#13]
@samhoogantink  Hello, I try to test your Fortnite Api with your testing code, but when I try to get the User Id that not work and I have this error log

array(4) { ["success"]=> bool(false) ["location"]=> string(3) "nyc" ["error"]=> array(2) { ["code"]=> string(5) "xx004" ["message"]=> string(15) "Path not found." } ["data"]=> array(0) { } }

can you please help me ? 

Thank

**Comment by YoungChief** [comment]
If I read the error correctly then it's a problem in the pathfinding that only @samhoogantink can fix.

**Comment by hadouken111** [comment]
@youngchief-btw Thank you for your response, I would like to have help from @samhoogantink , but apparently no one is ready to help me: /

**Comment by youngchief-btw** [comment]
@hadouken111 If I remember, @samhoogantink gave ownership of the project to some other person, and he announced it on his discord server. Need a link or the exact owner? Also not sure if it was complete ownership but ill check and get back to you as soon as possible!

**Comment by hadouken111** [comment]
@youngchief-btw Thank you for your answer, I did not know so is there an alternative to this API? and reliable because I try another API but obviously the stats are not good

**Comment by samhoogantink** [comment]
Sorry, I don't maintain this API anymore.
