### ISSUE TITLE
please more explain

### ISSUE THREAD

**Issue by AitGamers** [samhoogantink/Fortnite-API#4]
hello,
[1] you say "Place the file in your PHP directory and include it in your PHP files."
i'm downloaded more than 12 php files, any one will include in my php files ?
[2] how i can use it to get player stats ? how i can define platform and username with variables ?
thank you.

**Comment by exqlusive** [comment]
@AitGamers 

It looks like you are programming in PHP. Maybe it is easier for you, to not use @samhoogantink wrapper. You can find the Postman details here: https://documenter.getpostman.com/view/4499368/RWEjoGqD . 

If you wish to retrieve stats with @samhoogantink wrapper: https://fortniteapi.com/docs/open/4
