### ISSUE TITLE
,string(16) "unknown_platform"

### ISSUE THREAD

**Issue by DevTimeEU** [samhoogantink/Fortnite-API#6]
Hello, I have a problem.
After, download, and install your Fortnite-API, I get this:
,string(16) "unknown_platform"

My code is:
`<?php
require_once 'fortnite-api/Autoloader.php';

$api = new FortniteClient;
$api->setKey('MY_KEY'); // my key is on website

$user = $api->user->id('Trix_FollOoW_YT');

$api->user->uid = $user;

$data = $api->user->stats('ps4', 'alltime');

var_dump($data);
?>`

**Comment by samhoogantink** [comment]
-
